# Generated by Django 3.1 on 2020-08-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoiceitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('product_qnty', models.CharField(default='', max_length=100)),
                ('product_amount', models.CharField(default='', max_length=100)),
                ('invoice_i_fk_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ocr.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Invoicedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(default='', max_length=100)),
                ('invoice_company_name', models.CharField(default='', max_length=100)),
                ('invoice_total_price', models.CharField(default='', max_length=100)),
                ('invoice_address', models.CharField(default='', max_length=100)),
                ('invoice_email', models.CharField(default='', max_length=100)),
                ('invoice_phoneno', models.CharField(default='', max_length=100)),
                ('invoice_date', models.DateField(default='')),
                ('invoice_fk_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ocr.invoice')),
            ],
        ),
    ]
