# Generated by Django 3.1 on 2020-08-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedata',
            old_name='invoice_address',
            new_name='GSTIN',
        ),
        migrations.RenameField(
            model_name='invoicedata',
            old_name='invoice_company_name',
            new_name='Pan_no',
        ),
        migrations.RenameField(
            model_name='invoicedata',
            old_name='invoice_email',
            new_name='Shipping_charge',
        ),
        migrations.RenameField(
            model_name='invoicedata',
            old_name='invoice_fk_id',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='invoicedata',
            old_name='invoice_phoneno',
            new_name='invoice_total_tax_price',
        ),
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='invoice_i_fk_id',
            new_name='invoice',
        ),
    ]
