# Generated by Django 3.1 on 2020-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_auto_20200810_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_digitized',
            field=models.BooleanField(default=False, verbose_name='Is Degitized'),
        ),
    ]
