# Generated by Django 3.1 on 2020-08-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_invoice_trackingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='trackingId',
            field=models.CharField(default='rrwmbdnnrp', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='invoice_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
