# Generated by Django 3.1 on 2020-08-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_auto_20200810_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='is_digitized',
            field=models.BooleanField(default=True, verbose_name='Is Degitized'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='trackingId',
            field=models.CharField(default='hocembttma', max_length=100),
        ),
    ]
