# Generated by Django 3.1 on 2020-08-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_auto_20200810_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='trackingId',
            field=models.CharField(default='jxyazohhxr', max_length=100),
        ),
    ]
